POST {{host}}/api/refreshToken
Content-Type: application/json

{
    "refresh_token": "{{refresh_token}}"
}

> {%
client.global.set("user_token", response.body.access_token);
client.global.set("refresh_token", response.body.refresh_token);
    client.test("status code 200", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
